Java program to multiply two numbers
javaistic/javaistic pull request #371
Opened 2022-10-14 21:30 UTC by AbhishekJadhav2002

**Issue:** #201 

### Description

Added Java program to multiply two numbers
Added package-log.json inside [.gitignore](https://github.com/AbhishekJadhav2002/javaistic/blob/java-program-to-multiply-two-numbers/.gitignore)
fixes #201

2022-10-14 21:35 UTC, AbhishekJadhav2002 commented
@uiuxarghya For now I'm providing only one task per request.
Please suggest changes, if any.
As, my request get approved, that is, after getting familiar with the pattern, I will try to complete further tasks as well.

2022-10-14 22:14 UTC, uiuxarghya commented
> @uiuxarghya For now I'm providing only one task per request. Please suggest changes, if any. As, my request get approved, that is, after getting familiar with the pattern, I will try to complete further tasks as well.

Well done👍 @AbhishekJadhav2002. 
You have done a great job but it needs certain changes before merging.

2022-10-14 22:30 UTC, uiuxarghya requested changes

2022-10-14 22:30 UTC, uiuxarghya commented on src/navs/program.js
> +    pages['multiply-two-numbers'],
Add this line to the last in this list, 
You must follow the order of task list #201

2022-10-14 22:30 UTC, uiuxarghya commented on src/pages/programs/multiply-two-numbers.mdx
> +import { List, ListItemGood } from '@/components/List'
Replace it with
```jsx
import { TipInfo } from '@/components/Tip'
```

2022-10-14 22:30 UTC, uiuxarghya commented on src/pages/programs/multiply-two-numbers.mdx
> +```
If you know the Scanner class then it would be better to rewrite the code and output as per the Scanner class

2022-10-14 22:30 UTC, uiuxarghya commented on src/pages/programs/multiply-two-numbers.mdx
> +```
Also, Rewrite this code and output as per the Scanner class.

2022-10-17 13:53 UTC, AbhishekJadhav2002 commented
Also I wanted to ask that, is this project considered for Hacktoberfest @uiuxarghya

2022-10-17 19:33 UTC, uiuxarghya commented
> Also I wanted to ask that, is this project considered for Hacktoberfest @uiuxarghya

Yes, it is.

2022-10-17 19:38 UTC, uiuxarghya approved these changes

2022-10-17 19:38 UTC, merged

2022-10-17 19:40 UTC, uiuxarghya commented
Thanks a lot @AbhishekJadhav2002  for contributing to this repo. 😃✨